name: Tests
on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [latest, 1.49.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Sentry CLI
        uses: ./
        with:
          version: ${{ matrix.version }}
          url: ${{ secrets.SENTRY_URL }}
          token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          organization: ${{ secrets.SENTRY_ORGANIZATION }}
          project: ${{ secrets.SENTRY_PROJECT }}
      - name: Display Sentry CLI info
        run: |
          sentry-cli --help
          sentry-cli info
      - name: Make release
        if: contains(matrix.os, 'ubuntu') && matrix.version == 'latest'  # do not duplicate releases
        run: |
          VERSION=`sentry-cli releases propose-version`
          sentry-cli releases new "$VERSION"
          sentry-cli releases set-commits "$VERSION" --auto
          sentry-cli releases files "$VERSION" upload-sourcemaps ./dist \
            --rewrite \
            --ext map \
            --validate \
            --verbose \
            --strip-common-prefix
          sentry-cli releases finalize "$VERSION"
      - name: Send test event
        if: contains(matrix.os, 'ubuntu') && matrix.version == 'latest'  # do not duplicate events
        run: |
          export SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          sentry-cli send-event -m "Hello from GitHub Actions"

